### PR TITLE
[EXPERIMENTAL] Enable SourceLink

### PR DESCRIPTION
**Pull request by jfversluis**
### Description of Change ###

Mainly testing this for another project, so don’t merge it, I will do it when ready :)

### CODE REVIEW

**Comment by vividos** [comment]
Interesting changes, I thought I already enabled SourceLink, but only followed a tutorial and couldn't test it thoroughly.

**Comment by jfversluis** [comment]
Ah did you now? What did you do to enable it?

**Comment by vividos** [comment]
My changes were in 82c2be0c4cda89dfb9536ea7b3ed794f6df097b4. I just tested with my app, FilePicker 2.1.18 and "Just My Code" ticked off, and I couldn't step into the PickFile() call.

**Comment by jfversluis** [comment]
Probably because of this: https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/pull/140/files#diff-650ae36e2fbf3ea95dd2be1cafb50bd7R66

That is why I couldn’t get it working with Xamarin.Forms.

Could you test the new beta one on NuGet?

**Comment by jfversluis** [comment]
@vividos did you get around to trying if sourcelink works with this one?

**Comment by vividos** [comment]
Sorry, not yet, but I try it out now.

**Comment by vividos** [comment]
I tried SourceLink by updating to the NuGet package 2.1.30-beta, disabling "Just my code" in VS and then stepping into a PickFile() call. Unfortunately it didn't work, I couldn't get into the FilePicker's code. I also checked the package with the NuGetPackageExplorer, and it has the Repository section, as mentioned in https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink
So I don't know what I'm doing wrong. Could you step into the FilePicker's code?

**Comment by jfversluis** [comment]
Hm maybe it doesn’t work yet for VS Windows with these types of projects. Leave it for now, we will look into it later :)

**Comment by vividos** [comment]
I'm sure I'm doing something wrong. You could compare with Xamarin.Essentials, I'm sure they got it working, but I also didn't debug into that NuGet.

**Comment by jfversluis** [comment]
Not necessarily, I think some changes are still needed in the debugger to fully support this. So maybe that hasn’t been implemented yet. I’m watching this closely for Xamarin.Forms so I will let you know when this should be good.

**Comment by vividos** [comment]
As I read that Xamarin Forms now supports SourceLink, we could merge this also, right?

**Comment by jfversluis** [comment]
Yep, just created a new pre-release version and used it with the latest VSMac preview bits and it worked!

**Pull request merged**
