### PR TITLE
Some issues with GoogleDrive, OneDrive for Android and iOS

### PR DESCRIPTION
**Pull request by ArtjomP**

### CODE REVIEW

**Comment by jfversluis** [comment]
It seems there is merged conflicts to be solved first

**Comment by ArtjomP** [comment]
I'm a little bit confused. What should I do?

**Comment by jfversluis** [comment]
I would like to get all the fixes for issues that are on the original repo into this one. I am working on setting up the CI and CD for this library and then this will become the primary source for the plugin which can be maintained from here on out.

Since another PR is already merged, I figure your PR isn't directly mergeable. I would like to ask you to implement your fix into this code as well, so we will have a complete and working library ASAP.

**Comment by ArtjomP** [comment]
It means I should fork your repo, change the code and start a pull request? Correct?

**Comment by jfversluis** [comment]
Correct

**Comment by ArtjomP** [comment]
Ok. I'll try

**Comment by ArtjomP** [comment]
Hi there. I've closed this pull request and opened another one. Happy New Year!

**Pull request closed without merging**
