### PR TITLE
Project fixes

### PR DESCRIPTION
**Pull request by vividos**
I collected the changes from pull request #22 that have nothing to do with Android OneDrive here. The changes can be merged without waiting for that pull request. Based on master branch. If requested, I can also rebase this pull request on the develop branch.

### CODE REVIEW

**Comment by jfversluis** [comment]
#22 was already merged. Is this still relevant?

**Comment by vividos** [comment]
Yes, this is still relevant. Pull Request #22 only contained the changes for the content:// URLs on Android, and this PR contains general project fixes.

**Review by jfversluis — APPROVED** [review]

**Comment by jfversluis** [comment]
This broke the build.. What did you base this on? Develop should be the one you're doing work on. Then when a stable version is on develop, I merge it to master.

**Comment by vividos** [comment]
Thanks for sorting this out! I know git, but pull requests are rather new to me. I'm looking forward to a stable version and NuGet package!

**Pull request merged**
