### PR TITLE
Add a GetStream Method to the API

### PR DESCRIPTION
**Pull request by kilimnik**
### Description of Change ###

I added a GetStream Mthod for each platform, so you could access the stream from a file a user picked later just from the file path.
It is usefull if you for example want to forward a file via the MessagingCenter, you now can forward the file path and access the stream via this method.

### Platforms Affected ### 
All Platforms

Unfortunately I couldn't test every platform because of weird errors in my VS.

### CODE REVIEW

**Comment by EvoPulseGaming** [comment]
One issue I found its that if you pick the same file twice, it will crash due to already being added to token dictionary. (at least in the UWP version) 

Add a check like so:

`            if (tokenDictionary.ContainsKey(file.Path))
            {
                tokenDictionary[file.Path] = t;
            }
            else
            {
                tokenDictionary.Add(file.Path, t);
            }`

**Comment by EvoPulseGaming** [comment]
Maybe change this function name to GetStreamFromFile? (It totally had me confused with the other GetStream)

One issue I found its that if you pick the same file twice, it will crash due to already being added to token dictionary. (at least in the UWP version)

Add a check like so:
`
if (tokenDictionary.ContainsKey(file.Path)) 
{ tokenDictionary[file.Path] = t; } 
else
{ tokenDictionary.Add(file.Path, t); }`

One last thing, this is IMPORTANT:
You need to revert the pickfile return back to
`            return new FileData(file.Path, file.Path.Substring(0,
                file.Path.Length - file.Name.Length),
                file.Name,
                () => file.OpenStreamForReadAsync().Result);
` 
on uwp, because its causing a 50/50 chance of an await lock. Not sure why, but changing this back stopped this issue. We already have a direct path with 'file' no need to use your getter that re-routes through tokenDictionary lookup.


Also maybe GetStreamFromPath should return an empty stream on error instead of null....

**Comment by vividos** [comment]
In the past we had some issues reported that after picking and waiting some time, the file wasn't available anymore. On iOS the picked file is copied to an inbox folder that is occasionally cleaned by iOS. On Android the ContentProvider could report that the content isn't available anymore. How would you handle these cases?

**Comment by kilimnik** [comment]
We could store the file in a temprary cache somewhere.

**Comment by EvoPulseGaming** [comment]
@vividos the native URI for each respective platform should also handle this. I'm working on my own version of this, where folder picking is possible, I have uwp and android versions setup so far, I'll be looking at iOS in a day or two.

Another thought, a combination of this stream getter and URI should allow you to get a file whenever you please as it's basically "re-picking" the file. Provided permissions stick (I know it does for Android)

**Comment by EvoPulseGaming** [comment]
I've implemented this and a bunch of other things in my fork of this project.
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/pull/168
If interested in where this project is going, please help with Tizen/WatchOS/TVOS as I do not own these devices. Is there a good chance that WatchOS and TVOS can be unified with iOS?

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Pull request closed without merging**
