### PR TITLE
Merge branch 'develop' into master

### LINKED ISSUE #112: Are permissions really needed on Android?
I created a pull request that requested the permission on run-time but I just found a [StackOverflow ](https://stackoverflow.com/questions/48045626/chooser-created-with-createchooserintent-title-doesnt-display-a-title) answer that says:

>  "Does ACTION_GET_CONTENT with setType("image/*) not need a permission to read external storage?" -- correct. On Android 4.3 and older, you do not need a permission to read external storage in general. On Android 4.4+, ACTION_GET_CONTENT should return a Uri with a content scheme, not a file scheme, and you have temporary rights to access the content identified by that Uri. 

If that's the case, maybe the FilePicker Plugin can work completely without permissions on Android?

### PR DESCRIPTION
**Pull request by vividos**
### Description of Change ###

This PR contains the merge from develop to master, with the following changes:

#109: Request of permissions in the plugin
#112: Adding of permissions to plugin
cleanup and reformatting of code

@jfversluis Please remove the "-beta" suffix from the version in AppVeyor before applying this PR - this version should be our latest non-beta version. Afterwards you can add it again, as I will work on the multi-targeting. Thanks!

### Issues Resolved ### 

- fixes #109
- fixes #112

### Platforms Affected ### 

- Android

### CODE REVIEW

**Comment by jfversluis** [comment]
Hm, I'll remove the tag. Maybe we should come up with something else for this. Maybe adding a tag if we want to release a version or something? This is not ideal ;)

**Review by jfversluis — APPROVED** [review]

**Comment by vividos** [comment]
Hmm no it isn't. Maybe just add the -beta suffix when building on develop branch, and master is always a non-beta build.
Thanks for merging!

**Comment by jfversluis** [comment]
Yeah, I thought about that. The problem is, as far as I can see in AppVeyor then it need to be two separate build definitions. The version numbers would go out of sync for the beta packages and actual ones. Not sure if it would really matter though

**Comment by vividos** [comment]
Maybe you could set a ${suffix} value using pretzel Powershell based on what git branch you are and add that to the version. Only works when the appveyor.yml is in the repository, though, I guess. Or maybe go with an Azure build...

**Pull request merged**
