### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by jfversluis**
As per #116 going to trunk based development

### CODE REVIEW

**Comment by jfversluis** [comment]
Hmm this doesn't look good 🤔

**Comment by vividos** [comment]
I fear this has to be merged by hand. Can't do it now, sorry!

**Comment by jfversluis** [comment]
I did it! There were changes in master that weren't in develop... All the more reason to get rid of this way :P

Can you carefully check if it still makes sense?

**Comment by vividos** [comment]
Hmm develop is correct, but master is 82 commits behind...

**Comment by vividos** [comment]
And the uwp implementation is missing

**Comment by jfversluis** [comment]
Alright I give up... When you have time could you have a look maybe? :)

**Comment by vividos** [comment]
I think the last commit ea8feba was in the wrong direction, it deleted some files. You should reset develop back to the 752f6b6 commit. I'll take a look in the evening.

**Pull request closed without merging**
