### PR TITLE
Multitarget

### PR DESCRIPTION
**Pull request by pictos**
Hi, I taken the liberty to change this project to multi-targeting, now it's more easy to implement new features and mainten. I add a sample project too, i can't test all scenarios, if you can test it's very good. I hope you like it ^^

### CODE REVIEW

**Comment by jfversluis** [comment]
Hi Pedro!

Awesome stuff! It just doesn't seem to build. Is this because the build has to be done differently now? Could you please check out the output: https://ci.appveyor.com/project/jfversluis/filepicker-plugin-for-xamarin-and-windows-5pvwc/builds/20203412

From what I can see it stops at building the NuGet packages, probably because of the multi-targeting which outputs the binaries in a different folder?

Also, and don't get me wrong, I am very grateful for this, but next time it would be great to open an issue first and checking with us if this is something we want and need and we can talk about it for a bit. Because now it comes fairly out of the blue.

**Comment by pictos** [comment]
@jfversluis thanks for reply.

> From what I can see it stops at building the NuGet packages, probably because of the multi-targeting which outputs the binaries in a different folder?

The solution now has only one project, and all PlataformSpecific code exist in this one project. So the Build looking for "src\Plugin.FilePicker\Plugin.FilePicker.Android\bin\Release" , but the "Plugin.FilePicker.Android" doesn't exist anymore.

> Also, and don't get me wrong, I am very grateful for this, but next time it would be great to open an issue first and checking with us if this is something we want and need and we can talk about it for a bit. Because now it comes fairly out of the blue.

Sure, I'm sorry for that, I think I acted on impulse. Can I suggest that within the Readme we put a topic on how to collaborate?

And if you want to test this implementation [here](https://github.com/pictos/FilePicker-Plugin-for-Xamarin-and-Windows/tree/Multitarget)

**Comment by vividos** [comment]
I have checked the commits and it seems you reformatted most of the code, which makes it hard to see actual changes you made. Did you make some changes? Maybe you can do the reformatting in a separate PR? My next change that I was planning to do would be exactly that - reformatting the code and improve source code documentation.
Thanks for the PR!

**Comment by pictos** [comment]
@vividos , hi! 

First of all, sorry for my impulse hehe. in really i just copied and pasted the old code into new solution. Could you give me more information about this separate PR?

**Comment by vividos** [comment]
@pictos Well, just look at the commits in this PR: The changes to .cs files are mostly whitespace, maybe tab to spaces and maybe line endings. That distracts from your actual goal, to enable multi-targeting. As soon as someone proposes another PR with some source changes, this PR won't apply cleanly anymore. So I suggest to first propose another PR with your code cleanup changes (e.g. only the changes in .cs files) and then rebase your multitarget PR onto this PR. Do you know what I mean?

**Comment by pictos** [comment]
@vividos ,
I think I understand what you mean. Anyway, with multi-targeting the specific projects will be deleted, hence the correct order would be ...

1. I create the multi-targeting project, without deleting the specific platafoma projects;
2. After reviewing you I delete the old projects leaving only the multi-targeting.

That's right? As soon as you confirm, I'll arrange that. : D

**Comment by vividos** [comment]
@pictos Let me review your changes first, the number of changes is quite big...

**Review by vividos — COMMENTED** [review]
As I already commented, these changes do multiple things:
- edit formatting (I guess auto-formatting in VS)
- renaming all the files and
- adjusting project files
No one can see from the diffs if there wasn't some accidental code changes. I will manually add the formatting changes to the current "develop" branch, though.
Besides, it seems you used an old copy of the code. FilePath has some comment changes, so it's possible these changes revert some bug fixes that were done.

**Review by vividos — COMMENTED** [review]
This change looks good. I'll hand pick it into the "develop" branch. I noticed that the FileData.shared.cs file is not the newest from the "develop" branch

**Review by vividos — COMMENTED** [review]
This commit changes the sample project name from Plugin.FilePicker.Sample to SampleFP. I think this change is not necessary. Also it seems you generated the sample projects with the new VS version?
And the commit message should be clear and meaningfil, but "AllChanges" tells me nothing about what the commit is.

**Review by vividos — COMMENTED** [review]
This change mostly consists of a new UWP test project named "Teste", but in develop branch there already is an UWP Forms test project. Again the commit message doesn't tell me what is in the commit.

**Comment by vividos** [comment]
First, thank you for your pull request. From viewing the changes, I think you have to pay attention what commits you do make, what they contain and what not. We happily accept PR as long as they are targeted at one issue, even when it's only code formatting or project renames.

About multi targeting... I don't understand exactly what it should improve. From looking at your changes, it has two drawbacks:
- It makes the projects less maintainable, by forcing other contributors to understand how multi targeting works
- Adding new implementations is more complicated now than adding a new project - you have to edit the innards of .csproj files now
Technically I guess it works, but what are the reasons for switching to it?

Third, from the discussions I understand we need a template for PRs (we already have one for issues) and maybe even a contributor's readme. I'll add one in the near future.

**Comment by pictos** [comment]
Overall, Multi-targeting is a new standard for Xamarin plugins, Xamarin Essentials, for example, is built using this approach. The biggest advantages are:

- Just one .netStandard project, so the solution becomes smaller and lighter, so the build proccess is more faster;

- Particularly I found it easier to maintain. Maybe you have found it difficult because I should not have refactored the best way possible, sorry for that;

- More easier to debug;

- To add new implementations you just need to add a new class or a new method;

I add these two videos about Multi-targeting recorded by James Montemagno:
[Convert Xamarin Libs to Multi-Target](https://www.youtube.com/watch?v=H41AyJ2Ef4w )
[New Plugin For Xamarin Templates For Visual Studio 2017](https://youtu.be/MSwH8NrtVCk)

The biggest disadvantage is that VS 2017 does not have very good support for the multi-target, after all it has appeared recently. However everything indicates that in the version of VS 2019 there will be better support for this. 

@vividos, do you have a communication channel like Microsoft Teams?

**Comment by vividos** [comment]
@pictos I just committed some changes to the develop branch, containing code formatting changes and documentation. If you'd like to try doing another pull request based on the latest develop version, you're welcome!

**Comment by pictos** [comment]
@vividos sure! I will :)

**Comment by vividos** [comment]
Very well, then I'm closing this PR. Thanks!

**Pull request closed without merging**
