### PR TITLE
Added support for file types across platforms

### PR DESCRIPTION
**Pull request by Dids**
- Added per platform file type support, so you can specify what kind of files you want the picker to support
- Updated iOS's picker to use the non-deprecated `UIDocumentPickerViewController`
- Minor tweaks, such as package updates

### CODE REVIEW

**Comment by Dids** [comment]
As mentioned in #24, UWP is entirely untested, but I've briefly tested that iOS, macOS and Android seem to work.

**Comment by Dids** [comment]
Just to update on the last commit: there was a rather nasty path formatting issue in the previous iOS implementation, where absolute paths were formatted as `file:///some/path/here`, instead of `/some/path/here`.

I previously worked around this by just wrapping the path in a `new Uri()`, but figured it would be better to properly fix it in the library itself, which was an easy fix.

**Comment by jfversluis** [comment]
So, what is the status on this? Should work across all? Just need to test UWP?

**Comment by Dids** [comment]
Yes, just needs UWP testing.

I'm also trying to get one or two iOS specific fixes included in this, although they're not directly related to the file type customization, but to how the iOS picker functionality is implemented and works in newer iOS versions.

**Comment by Dids** [comment]
Also slightly off topic, but I managed to fix the iOS sample (#2) as a part of this PR. :)

**Comment by jfversluis** [comment]
That is great on both!

Let me know whenever you're complete, I'll try to get UWP tested somewhere this week. When we're both done we can merge this.

**Comment by Dids** [comment]
There is one interesting mechanic with the iOS document picker. It allows to either import files, making a local copy of the file if necessary (currently the default), but also opening files directly.

I'm not actually sure which would make the most sense, since that would be more up to the type of application using the library, right?

Having the ability to directly edit files in iCloud Drive which don't necessarily belong to the current app would be great, but on the other hand, importing files is also important in my opinion.

One other thing I'm looking into is that I _think_ the document picker also allows saving/exporting data, which may prove useful if true.

Any thoughts on these?

**Comment by jfversluis** [comment]
I think we should stick with the default: importing the file. If we see the need for editing files directly, we'll manage then.

> One other thing I'm looking into is that I think the document picker also allows saving/exporting data, which may prove useful if true.

I don't quite get what you mean here

**Comment by Dids** [comment]
Yes, I agree. Never mind about the exporting part, I thought there was functionality for saving/exporting files using the picker.

**Comment by jfversluis** [comment]
In that light, how far along are you? If not ready, we could consider marking this as WIP until you're done. I see the latest changes have introduced some conflicts, sorry!

**Comment by Dids** [comment]
I think I'm actually done, just need to resolve the conflicts and fix the PR.

**Comment by Dids** [comment]
@jfversluis I've fixed the conflicts once again, so this PR _should_ be good to go. Appveyor seems to be failing to build the changes, but I'm not at all sure why.

**Comment by jfversluis** [comment]
Was due to the build configuration. Seems to build now!

**Review by jfversluis — APPROVED** [review]

**Pull request merged**
