### PR TITLE
Fix for Android OneDrive & Google drive

### PR DESCRIPTION
**Pull request by ArtjomP**
Fix for getting the DataArray from iCloud

### CODE REVIEW

**Comment by jfversluis** [comment]
Thanks!

There seems to be a build error for Android though?

> IOUtil.cs(143,33): error CS0117: 'FileData' does not contain a definition for 'ReadFully' [C:\projects\filepicker-plugin-for-xamarin-and-windows-5pvwc\src\Plugin.FilePicker\Plugin.FilePicker.Android\Plugin.FilePicker.Android.csproj]

**Comment by ArtjomP** [comment]
Sorry, my fault. I'll fix it

**Comment by ArtjomP** [comment]
Hi! I've added the skipped method.

**Comment by jfversluis** [comment]
Still doesn't seem to build my friend. Could you please have another look if still needed?

**Comment by ArtjomP** [comment]
It seems it can't merge because of the conflict. Only those with write access can resolve it

**Comment by ArtjomP** [comment]
@jfversluis may be I missed something else?

**Comment by jfversluis** [comment]
You should update your own repo with the latest changes from this one, merge there and add to this PR or open a new one. Since I don't know what exactly is in your changes or what the intent is behind it, it would be unwise to let me merge since I could easily miss something.

**Comment by ArtjomP** [comment]
Hi @jfversluis it seems my code is ready

**Comment by vividos** [comment]
Hi @ArtjomP, my pull request #22 should already contain your code. I tried to use your changes in order to fix the OneDrive bug. Could you check if the code is already in the "develop" branch? Then this pull request would be obsolete. Thanks!

**Comment by jfversluis** [comment]
Closed in favor of #44

**Pull request closed without merging**
