### PR TITLE
Merge to master

### PR DESCRIPTION
**Pull request by vividos**
This is the last set of changes for the bug fixes on Android and iOS. Let's make another public NuGet package, let the users test this and then do a non-beta release in a month or so. Thanks!

### CODE REVIEW

**Comment by vividos** [comment]
I hope this PR does the right thing - merging the latest develop changes to master so that we can publish a new public NuGet package.

**Comment by jfversluis** [comment]
I don't see any changes...? Or am I mistaken?

**Comment by vividos** [comment]
I might have selected the wrong source branch. I'll set it to "master"

**Review by jfversluis — APPROVED** [review]

**Comment by vividos** [comment]
Thanks!

**Pull request merged**
