### PR TITLE
Multi targeting

### PR DESCRIPTION
**Pull request by vividos**
### Description of Change ###

This PR changes the project to use a single, multi-targeting project for all platforms. I moved all implementation files from their subdirectories to the "Plugin.FilePicker" folder, apart from the Android implementation that resides in the "Android" subfolder. I also updated the sample projects and made some classes internal that are only used inside the plugin. I also made ReadFully() internal.

The NuGet package is now built during build, the infos for the package are in the .csproj file. I increased the version to 2.1.0-beta. This PR won't likely build in AppVeyor, as there is only one project now, and no .nuspec file anymore.

I didn't rename any classes or namespaces, but with the more compact project structure, we could lose the "Abstractions" namespace in a future PR.

@jfversluis I would let you do reviewing the PR and the merging. After porting the project to multi-targeting, I'm now more convinced that the change is good. The project got more lean and clearly laid out.

### Issues Resolved ### 

None. Previous PR was #110.

### Platforms Affected ### 

All. The NuGet package behaves the same in my Xamarin Forms project.

### CODE REVIEW

**Comment by jfversluis** [comment]
Changed the whole thing over to Azure DevOps and made it work. I might also have a solution for the beta and non-beta now. To make that work, we would have to switch to trunk based development though. That means; just the master branch and feature branches. Any thoughts?

**Comment by vividos** [comment]
Azure DevOps is ok for me, and also trunk based development.

What's missing for this PR is GitHub integration for Azure DevOps, so that the build checks for this PR works.

**Comment by jfversluis** [comment]
Let's get this merged into develop and I'll open a PR to master. Then it should check the build etc. Then, when it is merged in master I will delete the develop branch.

**Comment by vividos** [comment]
Thanks!

**Pull request merged**
