### PR TITLE
Fixed Path

### PR DESCRIPTION
**Pull request by muhaym**
Was returning File Url which cannot be used for file operations from PCL / Shared Project, instead of returning actual Path.

### CODE REVIEW

**Comment by jfversluis** [comment]
Hi @muhaym!

Thank you so much for your efforts! Could you please investigate a little on this change. I seem to remember that something has changed some code to actually implement more of an URL. But maybe that was just for Android.

Also could you describe what problem this solves exactly and where the actual change is? Because there is a lot of noise with whitespaces that have been added or removed. Not a problem in itself since I didn't set any hard coding standards, but it makes it hard to see where the actual change is.

Thanks!

**Comment by muhaym** [comment]
@jfversluis  Sorry about the white space, the change is simple.

I have added comment to the code, please check file changed for line 63

**Comment by jfversluis** [comment]
I see! Did you find anything on the other link change?
Does this work for both local files, iCloud filed, Folder files.. etc?

**Comment by muhaym** [comment]
Tried with Local File, iCloud file and One Drive / Dropbox kind of files, everything positive.

**Pull request merged**
