### PR TITLE
Ability to specify maximum allowed file size. File data is not returned if file exceed specified size.

### PR DESCRIPTION
**Pull request by JayMansel**

### CODE REVIEW

**Comment by vividos** [comment]
@JayMansel After working a bit with the FilePicker source, I think the better approach to the issue you're facing is what I mentioned in #38. Don't bother getting DataBytes and instead use GetStream() to get the underlying steam and read from there. This way you can also limit how many bytes to read without modifying FilePicker. What do you think?

**Comment by jfversluis** [comment]
@JayMansel could you please respond? Or if you're not up for it anymore, no hard feelings but please let us know, else we'll close it soon. Thanks!

@vividos in the latter case, how do we go about this? Is there something in the code for this already?

**Comment by vividos** [comment]
@jfversluis do you mean how to read only X bytes from the steam? Well, GetStream() returns a .NET steam that you can do anything that you want, including doing after say 1 MB worth of data.

**Comment by jfversluis** [comment]
I think there is/was a problem that if the file is too large, it would just return an empty stream. But maybe we should just go out with this new code and see what happens. If someone ever opens an issue about this, we'll just see about it then

**Comment by vividos** [comment]
I thought the problem was when accessing DataArray, the app would they to load the whole file into memory, which fails if RAM is exhausted.
@JayMansel can you comment on that?

**Comment by vividos** [comment]
I think we can close this PR, the solution to the problem is already explained in the comments above. @JayMansel thanks for your contribution, though!

**Comment by JayMansel** [comment]
@vividos @jfversluis So sorry for not replying. Was incredibly busy with new projects etc etc and went on a mass 'unsubscribe' spree :-x

Cheers for the fix, will look to update and make use of the GetStream() method instead! :)

**Pull request closed without merging**
