### PR TITLE
Multi-Targeting project

### PR DESCRIPTION
**Pull request by pictos**
### Description of Change ###

Change the project to multi-targeting. Now I have made more fragmented commits, to facilitate the analysis of the code.

### Platforms Affected ### 
All Plataforms

### Tests ### 
I did tests on the Android, UWP and WPF platforms and they all worked correctly. Unfortunately I do not have a MAC so I could not test iOS and MAC. I would be happy if you could do this for me :)

### CODE REVIEW

**Comment by vividos** [comment]
I the commits I still can't see what you changed in all the .cs files. In order for git (and github) to show me what has changed, the delete and add operations must go into one commit so that they are recognized as a rename operation.

**Comment by pictos** [comment]
@vividos  sorry for delay. I don't made changes in code... Just copy and paste. I run the sample project before my changes and after, to ensure that they would have the same behavior.

**Comment by vividos** [comment]
The problem is when you don't make the changes in one commit, git and github doesn't get that it's a rename only. For git you added some files, and in the next commit you removed some other files.

**Comment by vividos** [comment]
I just had a try at merging the PR. It seems that you based this PR not on the current develop, but on some previous version. When I would merge that PR, bug fixes and documentation changes would get lost. I'll try to merge the changes you made by hand, but that will take a while. As this PR won't be applied, I'm closing this. I'll publish a new PR as soon as I have made the manual merge.

**Comment by pictos** [comment]
@vividos ok. If you need more information, let me know.

**Comment by vividos** [comment]
For anybody interested in my progress, this is my experimental branch:
https://github.com/vividos/FilePicker-Plugin-for-Xamarin-and-Windows/tree/multi-targeting
I'm not quite happy with the changes, so the branch will move around a little bit.

**Pull request closed without merging**
