### PR TITLE
Initial support for folder picking and also initial platform support for tizen, watchos, and TVOS

### PR DESCRIPTION
**Pull request by EvoPulseGaming**
*It was suggested to move this to xamarin essentials, but due to them dragging their feet over a very SIMPLE pull request, into their EXPERIMENTAL dev branch. I'm stuck in a bind. I've reverted to using this version. My branch is 100% working as far as I know. I've also updated it since this PR.

I'm not sure if the samples work after these last few updates.

Original
So this isn't a real pull request, I'm just pushing this for visibility. Once this is fully complete, this could actually become a real request

I've basically stitched together a bunch of things found around the web and will need help to complete this.

### CODE REVIEW

**Comment by vividos** [comment]
First, thanks for your pull request. I have a few comments, though...
I think for almost every project that cares about the changes being made to it, it's best to separate changes from different domains (housekeeping, updating projects, adding new functionality) into separate pull requests. They're easier to review and quicker to apply, and in the end better to handle by the project.
For the OpenFile() functions... we never figured out what they are supposed to do, so we marked them obsolete, to be removed in a future version.
And finally... there's also efforts to to file picking into Xamarin Essentials (https://github.com/xamarin/Essentials/pull/975), which is and will be supported by Microsoft employees for the foreseeable time. I think it would be best to direct your efforts in this direction.

**Comment by EvoPulseGaming** [comment]
I see, I had no idea about essentials working on that. The only thing I have to add then is folder picking xD, I'll keep an eye on it.

**Comment by vividos** [comment]
Nevertheless, feel free to contribute your other, non-folder-picking changes back to the project, perhaps in another PR. Thanks!

**Comment by EvoPulseGaming** [comment]
So I've started to convert it to essentials, but they appear to be on vacation or generally slow to respond... I'm going to re open this just so people can see this and pick at it.

**Comment by jfversluis** [comment]
Closing this since this project will retire, please check out [Xamarin.Essentials](https://github.com/xamarin/Essentials/tree/main/Xamarin.Essentials/FilePicker) which now has a FilePicker based on this one.

**Pull request closed without merging**
